# -*- coding: utf-8 -*-
"""text_editor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6BunEqt9UoVXRp57dZExR4WGR6OnRm9
"""

import os

def display_menu():
    print("Simple Text Editor")
    print("1. Create New File")
    print("2. Open Existing File")
    print("3. Save Current File")
    print("4. Edit Current File")
    print("5. Exit")

def create_new_file():
    filename = input("Enter new file name: ")
    if os.path.exists(filename):
        print("File already exists. Try a different name.")
    else:
        with open(filename, 'w') as file:
            print(f"{filename} created successfully.")
    return filename

def open_existing_file():
    filename = input("Enter file name to open: ")
    if not os.path.exists(filename):
        print("File does not exist.")
        return None, ""
    else:
        with open(filename, 'r') as file:
            content = file.read()
        print(f"{filename} opened successfully.")
        return filename, content

def save_file(filename, content):
    with open(filename, 'w') as file:
        file.write(content)
    print(f"{filename} saved successfully.")

def edit_file(content):
    print("Enter your text below. Type 'SAVE' on a new line to save and exit editing mode.")
    lines = []
    while True:
        line = input()
        if line.strip().upper() == 'SAVE':
            break
        lines.append(line)
    new_content = "\n".join(lines)
    return new_content

def main():
    current_file = None
    current_content = ""

    while True:
        display_menu()
        choice = input("Choose an option: ")

        if choice == '1':
            current_file = create_new_file()
            current_content = ""
        elif choice == '2':
            current_file, current_content = open_existing_file()
            if current_file:
                print("Current Content:")
                print(current_content)
        elif choice == '3':
            if current_file:
                save_file(current_file, current_content)
            else:
                print("No file is currently opened or created.")
        elif choice == '4':
            if current_file:
                current_content = edit_file(current_content)
            else:
                print("No file is currently opened or created.")
        elif choice == '5':
            print("Exiting the editor.")
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()